### ISSUE TITLE
Request logging level is too low (info, should be debug)

### ISSUE THREAD

**Issue by 54sledgehammer45** [felixlindstrom/python-salesforce-api#15]
Hi,

First of all thanks a lot for providing such a nice client and making one aspect of the salesforce API simple.

While using the client, the following line is outputting logs that cannot be easily disabled in the logging config. The root logger is being used which means in order to disable this log line, the root logger itself has to switch from `INFO` to a higher filter.

https://github.com/felixlindstrom/python-salesforce-api/blob/da97c2290095a0925f3076bf9783aebfb995dc2d/salesforce_api/core.py#L19

Would it be possible to use a logger specific to the package (e.g "salesforce_api") or reduce this log level to `debug`?

Cheers

**Comment by felixlindstrom** [comment]
Hello,

Sorry for late reply.

You are completely correct, the logging level was way too low. The logging should probably not happen at all, as result data is quite large in a lot of cases, and there's no real need to log it.

It was removed, due to this.
