### ISSUE TITLE
Getting ImportError Exception in importing from salesforce_api.models.retrieve import Type

### ISSUE THREAD

**Issue by shrivastavaanurag** [felixlindstrom/python-salesforce-api#2]
I was using salesforce-api 0.1.35 I am getting an error in importing 

**from salesforce_api.models.retrieve import Type**

An exception has occurred: ImportError
cannot import name 'Type' from 'salesforce_api.models.retrieve' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/salesforce_api/models/retrieve.py)

**Comment by felixlindstrom** [comment]
The location of Type changed, but the documentation did not reflect this change. This was fixed in PR issue-2.
